---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: po1-gateway
spec:
  template:
    spec:
      containers:
      - name: po1-gateway
        env:
        - name: ENV_TYPE
          value: "development"
        - name: PAYPAL_URL
          value: "development.paypal.com"
        - name: DB_USER
          value: "dev_username"
        - name: DB_PASSWORD
          value: "dev_password"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080

