---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: po1-gateway
spec:
  template:
    spec:
      containers:
      - name: po1-gateway
        image: 236731556556.dkr.ecr.eu-west-1.amazonaws.com/po1/http-https-echo:31
