apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: po1-pr123
nameSuffix: -dev-pr123

resources:
- ../../base

components:
- ../../variants/dev
- ../../variants/pr123

patchesStrategicMerge:
- configmap.yml
