apiVersion: v1
kind: ConfigMap
metadata:
  name: po1-gateway
data:
  ENVIRONMENT: unknown
  NAME: po1
  NODE_ENV: production
  HOST: '0.0.0.0'
  PORT: '8080'
  INTROSPECTION: 'true'
  STACKTRACES: 'true'
  REMOTE_URL_SERVICE1: http://dev-po1-service-demo.po1.svc.cluster.local
  REMOTE_GRAPHQL_ROUTE: /graphql
