---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: po1-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: po1-gateway
  template:
    metadata:
      labels:
        app: po1-gateway
    spec:
      containers:
      - name: po1-gateway
        imagePullPolicy: Always
        image: 236731556556.dkr.ecr.eu-west-1.amazonaws.com/po1/po1-gateway:latest
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - configMapRef:
            name: po1-gateway
