---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: po1-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: po1-gateway
  template:
    metadata:
      labels:
        app: po1-gateway
    spec:
      containers:
      - name: po1-gateway
        imagePullPolicy: Always
        image: k8s.gcr.io/e2e-test-images/echoserver:2.5
        ports:
        - containerPort: 8080
