---
apiVersion: v1
kind: Service
metadata:
  name: po1-gateway
spec:
  type: ClusterIP
  selector:
    app: po1-gateway
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
