apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa
namePrefix: qa-eu-

resources:
- ../../base

components:
  - ../../variants/qa

patchesStrategicMerge:
- deployment.yml
- version.yml
- settings.yml


