---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: po1-gateway
spec:
  template:
    spec:
      containers:
      - name: po1-gateway
        env:
        - name: ENV
          value: "uat-eu"
        - name: GPU_ENABLED
          value: "1"
